sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - wget
      # Package list from http://bazel.io/docs/install.html
      - oracle-java8-installer
      - pkg-config
      - zip
      - zlib1g-dev

install:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.2.3/bazel-0.2.3-installer-linux-x86_64.sh'
  - chmod +x bazel-0.2.3-installer-linux-x86_64.sh
  - ./bazel-0.2.3-installer-linux-x86_64.sh --user

script:
  - bazel version
  - script/setup
  - bazel test :service_control_client_impl_test --test_output=all
